### ISSUE TITLE
Unlock access card functionality

### ISSUE THREAD

**Issue by T-REX-XP** [Saratoga79/Proyecto-PACEficator-Project#543]
Hi. I would like to request Unlock access card functionality. Is it possible? 
It will be very useful. Thanks.
![Screenshot_20191110-134922_Amazfit](https://user-images.githubusercontent.com/4560084/68543989-f0685a00-03c6-11ea-9dbd-dec22abf68b2.jpg)
.

**Comment by Saratoga79** [comment]
I don't think so.
Please, stick to XDA threads for main discussions, as this is mean to be only for translations.
